VIETNAMESE_NAMES = [
    "Nguyễn Thị Như Quỳnh",
    "Lê Hoàng Quân",
    "Đinh Văn Phượng",
    "Nguyễn Echam Samuel",
    "Nguyễn Xuân Sang",
    "Lê Phú Quý",
    "Lý Quốc Quyền",
    "Bùi Minh Quân",
    "Nguyễn Ngọc Sơn",
    "Bùi Duy Qúy",
    "Võ Hoàng Phương",
    "Trần Minh Phương",
    "Phan Duy Quốc",
    "Nguyễn Vũ Ngọc Quyên",
    "Trương Trọng Quân",
    "Phạm Minh Quân",
    "Võ Thanh Sanh",
    "Nguyễn Minh Phương",
    "Nguyễn Viết Sơn",
    "Vũ Hoàng Hải Sơn",
    "Nguyễn Hải Sơn",
    "Nguyễn Vũ Trường Sơn",
    "Trần Minh Sang",
    "Nguyễn Trung Sơn",
    "Lê Quang",
    "Vũ Thị Phương",
    "Nguyễn Văn Sơn",
    "Lê Anh Sơn",
    "Võ Tiến Sĩ",
    "Phan Đức Sơn",
    "Trần Thế Sơn",
    "Vũ Hồng Tâm",
    "Nguyễn Minh Tân",
    "Lê Hà Xuân Thái",
    "Nguyễn Ngọc Phương",
    "Bùi Anh Tài",
    "Dương Chí Tâm",
    "Phạm Thanh Quốc",
    "Lê Trường Sa",
    "Lưu Nguyễn Quốc Sơn",
    "Ngô Vũ Sang",
    "Lê Công Tài",
    "Đỗ Minh Tâm",
    "Trần Thị Minh Sương",
    "Trần Văn Tài",
    "Lê Văn Tài",
    "Vũ Thị Hoài Sơn",
    "Dương Thanh Tâm",
    "Hồ Quốc Tài",
    "Huỳnh Lê Tấn Tài",
    "Huỳnh Hữu Tâm",
    "Nguyễn Anh Tấn",
    "Nguyễn Ngọc Thân",
    "Đoàn Thanh Tân",
    "Vũ Minh Thái",
    "Đặng Xuân Thanh",
    "Vũ Văn Thành",
    "Lê Duy Thắng",
    "Hồ Nguyễn Xuân Thanh",
    "Trần Tất Thắng",
    "Nguyễn Chí Thanh",
    "Phan Xuân Thắng",
    "Bùi Minh Thảo",
    "Đặng Văn Thắng",
    "Diệp Vương Thắng",
    "Đinh Xuân Thắng",
    "Lâm Văn Thành",
    "Nguyễn Tiến Thành",
    "Đàm Văn Thiện",
    "Nguyễn Văn Thanh",
    "Võ Đức Thảo",
    "Bùi Trung Thành",
    "Lê Tấn Thạnh",
    "Lê Tiến Thành",
    "Nguyễn Đình Thi",
    "Nguyễn Công Thành",
    "Lương Văn Thao",
    "Cao Bá Thành",
    "Nguyễn Hữu Thế"
]